[package]
name = "garage_pie"
version = "0.1.0"
authors = ["Jake Wharton <garage-pie@jakewharton.com>"]
edition = "2018"
license = "Apache 2.0"

[dependencies]
rppal = "0.11"
structopt = "0.3"
tide = "0.16"
async-std = { version = "1.8", features = ["attributes"] }
tide-tracing = "0.0.8"
tracing = "0.1"
tracing-subscriber = "0.2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
