name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'

jobs:
  debug_build_and_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --no-default-features

      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --no-default-features

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release_armv7_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: armv7-unknown-linux-musleabihf

      - run: sudo apt-get install binutils-arm-linux-gnueabihf

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --release --target armv7-unknown-linux-musleabihf

      - uses: actions/upload-artifact@v2
        with:
          name: normally-closed-armv7
          path: target/armv7-unknown-linux-musleabihf/release/normally-closed

  release_armv6_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: arm-unknown-linux-musleabihf

      - run: sudo apt-get install binutils-arm-linux-gnueabihf

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --release --target arm-unknown-linux-musleabihf

      - uses: actions/upload-artifact@v2
        with:
          name: normally-closed-armv6
          path: target/arm-unknown-linux-musleabihf/release/normally-closed

  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt

      - uses: actions-rs/cargo@v1
        name: cargo fmt
        with:
          command: fmt
          args: -- --check
