name: build and publish

on:
  push:
    branches:
      - trunk
    tags:
      - '*'

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt

      - uses: actions-rs/cargo@v1
        name: cargo fmt
        with:
          command: fmt
          args: -- --check

  debug_build_and_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: armv7-unknown-linux-musleabihf
          components: clippy

      - run: sudo apt-get install binutils-arm-linux-gnueabihf

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: garage_pie_debug
          path: target/armv7-unknown-linux-musleabihf/debug/garage_pie

  release_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: armv7-unknown-linux-musleabihf

      - run: sudo apt-get install binutils-arm-linux-gnueabihf

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v2
        with:
          name: garage_pie
          path: target/armv7-unknown-linux-musleabihf/release/garage_pie

  docker:
    runs-on: ubuntu-latest

    needs:
      - rustfmt
      - debug_build_and_checks
      - release_build

    steps:
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: |
            jakewharton/garage-pie
            ghcr.io/jakewharton/garage-pie
          tag-semver: |
            {{version}}
            {{major}}
            {{major}}.{{minor}}

      - uses: docker/login-action@v1
        with:
          username: jakewharton
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - uses: ffurrer2/extract-release-notes@v1
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')

      - uses: actions/download-artifact@v2

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: |
            garage_pie
            garage_pie_debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
